# =============================================================================
# AI EMAIL ROUTER - GOOGLE CLOUD BUILD CONFIGURATION
# =============================================================================

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/${PROJECT_ID}/email-router:${COMMIT_SHA}',
      '-t', 'gcr.io/${PROJECT_ID}/email-router:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/email-router:${COMMIT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/email-router:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'email-router',
      '--image', 'gcr.io/${PROJECT_ID}/email-router:${COMMIT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '0',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'ENVIRONMENT=production',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}',
      '--set-env-vars', 'GOOGLE_CLOUD_REGION=${_REGION}'
    ]

# Substitution variables
substitutions:
  _REGION: us-central1

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

# Build timeout
timeout: 1200s 