# =============================================================================
# SERVICE LEVEL AGREEMENT (SLA) CONFIGURATION
# Define response times and service commitments
# =============================================================================

# Response time commitments by category
response_times:
  support: 
    target: "within 4 hours"
    business_hours_only: true
    weekend_multiplier: 2.0  # 8 hours on weekends
    
  billing:
    target: "within 24 hours"
    business_hours_only: false
    weekend_multiplier: 1.0  # Same on weekends
    
  sales:
    target: "within 2 hours"
    business_hours_only: true
    weekend_multiplier: 4.0  # 8 hours on weekends
    
  general:
    target: "within 24 hours"
    business_hours_only: false
    weekend_multiplier: 1.0
    
  urgent:
    target: "within 1 hour"
    business_hours_only: false
    weekend_multiplier: 1.0

# Business hours definition
business_hours:
  timezone: "America/New_York"
  workdays: ["monday", "tuesday", "wednesday", "thursday", "friday"]
  start_time: "09:00"
  end_time: "17:00"
  
  # Holiday calendar (extend as needed)
  holidays:
    - "2024-01-01"  # New Year's Day
    - "2024-07-04"  # Independence Day
    - "2024-12-25"  # Christmas Day

# Escalation rules
escalation:
  # Automatic escalation if SLA is breached
  sla_breach:
    enabled: true
    escalate_after_percentage: 80  # Escalate at 80% of SLA time
    
  # Manual escalation triggers
  manual_triggers:
    - keyword: "urgent"
      immediate: true
    - keyword: "emergency"
      immediate: true
    - keyword: "vip"
      immediate: true
    - sender_domain: "bigclient.com"
      immediate: true

# Performance tracking
metrics:
  track_response_times: true
  track_resolution_times: true
  track_customer_satisfaction: true
  generate_sla_reports: true
  
  # SLA targets for reporting
  targets:
    first_response_percentage: 95  # 95% within SLA
    resolution_percentage: 90     # 90% resolved within target
    satisfaction_score: 4.5       # Out of 5

# Notification rules
notifications:
  sla_warning:
    enabled: true
    notify_at_percentage: 75  # Warn at 75% of SLA time
    notify_to: "manager@company.com"
    
  sla_breach:
    enabled: true
    notify_immediately: true
    notify_to: ["manager@company.com", "admin@company.com"]
    
  daily_summary:
    enabled: true
    send_time: "09:00"
    send_to: "manager@company.com" 